#!/bin/sh

. functions
VMd=`dirname $(readlink -f $0)`

TestRoot
if [ -z "$2" ]; then
	echo "Usage: $0 VMname /path/to/isofile"
	exit 1
fi

VMname=$1
isofile=$2
VMdir="$VMd/vm/$VMname"
TestVM $VMdir

if ! [ -e "$VMdir/$ConfFile" ]; then
	echo "This VM has no file $ConfFile! Exiting."
	exit 1
fi
if ! [ -e "$isofile" ]; then
	echo "This iso file does not exist."
	exit 1
fi

. $VMdir/$ConfFile
ISOp="$ISO"
if [ -n "$ISO" ]; then
	if [ "$ISO" = "$isofile" ]; then
		echo "Iso file hasn't changed. It remains: $ISO"
		exit 0
	fi
	r=$(grep  -v "^[ 	]*ISO=" "$VMdir/$ConfFile")
	cp "$VMdir/$ConfFile" "$VMdir/$ConfFile.sav"
	echo "$r" > "$VMdir/$ConfFile"
fi
echo "ISO=\"$isofile\"" >> "$VMdir/$ConfFile"

. $VMdir/$ConfFile
if ! [ "$isofile" = "$ISO" ]; then
	echo "Cannot set iso file! Please inspect $VMdir/$ConfFile."
	exit 1
fi
if [ -n "$ISOp" ]; then
		echo "Changed ISO file from $ISOp to $ISO"
else
	echo "Inserted ISO file: $ISO"
fi
p=`Status "$VMname"`
if [ "$p" -gt 0 ]; then
	echo "Please stop and restart the VM to this change takes effect."
fi
